LoginStartSolution/Controllers/AnagraficaController.cs
using Microsoft.AspNetCore.Mvc;
using LoginStartMenu.Models;
using System.Diagnostics;
using Newtonsoft.Json;
using LoginStartMenu.Models.Collection;
using Microsoft.Data.SqlClient;
using System;
using System.Data.SqlClient;
using System.IO;


namespace LoginStartMenu.Controllers
{
    public class AnagraficaController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;

        public AnagraficaController(ILogger<HomeController> logger, ApplicationDbContext context, IConfiguration configuration)
        {
            _logger = logger;
            _context = context;
            _configuration = configuration;
        }




        [HttpGet]
        public IActionResult Index()
        {
            var accessoJson = HttpContext.Session.GetString("AccessoUtente");
            if (!string.IsNullOrEmpty(accessoJson))
            {
                var accesso = JsonConvert.DeserializeObject<AccessoUtente>(accessoJson);
                return View(accesso);
            }
            return RedirectToAction("Index", "Login");
        }


        [HttpGet]
        public IActionResult Search()
        {
            var accessoJson = HttpContext.Session.GetString("AccessoUtente");
            if (!string.IsNullOrEmpty(accessoJson))
            {
                var accesso = JsonConvert.DeserializeObject<AccessoUtente>(accessoJson);
                return View(accesso);
            }
            return RedirectToAction("Index", "Login");
        }



        [HttpGet]
        public IActionResult UploadImage()
        {
            var accessoJson = HttpContext.Session.GetString("AccessoUtente");
            if (!string.IsNullOrEmpty(accessoJson))
            {
                var accesso = JsonConvert.DeserializeObject<AccessoUtente>(accessoJson);
                var utenti = _context.Utenti.ToList();
                ViewBag.utentiList = utenti;
               
                return View(accesso);
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public IActionResult UploadImage(IFormFile file, string user, string imageField)
        {
            if (file != null && file.Length > 0)
            {
                byte[] imageData;
                using (var memoryStream = new MemoryStream())
                {
                    file.CopyTo(memoryStream);
                    imageData = memoryStream.ToArray(); 
                }

                string connectionString = _configuration.GetConnectionString("DefaultConnection");

                if (string.IsNullOrEmpty(user))
                {
                    return BadRequest("Errore: ID utente non valido.");
                }

                string query = "";
                if (imageField == "Img1")
                {
                    query = "UPDATE Immagini SET img1 = @ImageData WHERE IdImmagine = @IdImmagine";
                }
                else if (imageField == "Img2")
                {
                    query = "UPDATE Immagini SET img2 = @ImageData WHERE IdImmagine = @IdImmagine";
                }
                else if (imageField == "Img3")
                {
                    query = "UPDATE Immagini SET img3 = @ImageData WHERE IdImmagine = @IdImmagine";
                }
                else if (imageField == "ImmagineProfilo")
                {
                    query = "UPDATE Immagini SET ImmagineProfilo = @ImageData WHERE IdImmagine = @IdImmagine";
                }

                if (!string.IsNullOrEmpty(query))
                {
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        connection.Open();
                        using (SqlCommand command = new SqlCommand(query, connection))
                        {
                            command.Parameters.AddWithValue("@ImageData", imageData);
                            command.Parameters.AddWithValue("@IdImmagine", user); 
                            command.ExecuteNonQuery();
                        }
                    }
                }

                return RedirectToAction("UploadImage");
            }

            return BadRequest("Nessun file selezionato.");
        }


    }
}

LoginStartSolution/Views/Shared/Components/ImageBox/ImageBoxViewComponent.cs
using LoginStartMenu.Models;
using LoginStartMenu.Models.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
public class ImageBoxViewComponent : ViewComponent
{
    private readonly ApplicationDbContext _context;

    public ImageBoxViewComponent(ApplicationDbContext context)
    {
        _context = context;
    }


    public async Task<IViewComponentResult> InvokeAsync()
    {
        var users = await _context.Utenti
            .Include(u => u.Immagine)
            .ToListAsync();

        return View(users);
    }

}

LoginStartSolution/Views/Shared/AnagraficaPartial/AdminPartialSearchAnagrafica.cshtml
@model LoginStartMenu.Models.Collection.AccessoUtente

<div class="container">
    @await Component.InvokeAsync("ImageBox")
</div>

LoginStartSolution/Views/Shared/AnagraficaPartial/AdminUploadImage.cshtml
<div class="container mt-4">
    <form asp-action="UploadImage" asp-controller="Anagrafica" method="post" enctype="multipart/form-data">
        <!-- Seleziona utente -->
        <div class="col-sm-4 form-group mb-4">
            <label class="mb-1" for="user">Seleziona utente:</label>
            <select name="user" class="form-control">
                <option value="" disabled selected>- Seleziona utente -</option> <!-- Primo elemento non selezionabile -->
                @foreach (var utente in ViewBag.utentiList)
                {
                    <option value="@utente.IdUtente">@utente.Username</option>
                }
            </select>
        </div>

        <!-- Seleziona campo immagine -->
        <div class="col-sm-4 form-group mb-4">
            <label class="mb-1" for="imageField">Seleziona campo immagine:</label>
            <select name="imageField" class="form-control">
                <option value="" disabled selected>- Seleziona immagine -</option> <!-- Primo elemento non selezionabile -->
                <option value="Img1">Img1</option>
                <option value="Img2">Img2</option>
                <option value="Img3">Img3</option>
                <option value="ImmagineProfilo">Immagine del profilo</option>
            </select>
        </div>

        <!-- Seleziona immagine -->
        <div class="col-sm-4 form-group mb-4">
            <label class="mb-1" for="file">Seleziona immagine:</label>
            <input type="file" name="file" class="form-control" />
        </div>

        <!-- Bottone per invio -->
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>

LoginStartSolution/Views/Shared/AnagraficaPartial/DipendentePartialRicercaAnagrafica.cshtml
<div class="profile-container">
    <div class="name">Nome Cognome</div>
    <div class="social-icons">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-twitter"></i>
        <i class="fab fa-linkedin-in"></i>
        <i class="fab fa-github"></i>
    </div>
</div>